export const CREATE_DESTINATION = "CREATE_DESTINATION"
export const UPDATE_DESTINATION = "UPDATE_DESTINATION"
export const DELETE_DESTINATION = "DELETE_DESTINATION"
export const SET_DESTINATIONS = "SET_DESTINATIONS"

