export const DELETE_DESTINATION_WISHLIST = "DELETE_DESTINATION_WISHLIST"
export const ADD_DESTINATION_WISHLIST = "ADD_DESTINATION_WISHLIST"
export const UPDATE_DESTINATION_WISHLIST = "UPDATE_DESTINATION_WISHLIST"