export const CREATE_DESTINATION_PRIVATE = "CREATE_DESTINATION_PRIVATE"
export const UPDATE_DESTINATION_PRIVATE = "UPDATE_DESTINATION_PRIVATE"
export const DELETE_DESTINATION_PRIVATE = "DELETE_DESTINATION_PRIVATE"
export const SET_DESTINATIONS_PRIVATE = "SET_DESTINATIONS_PRIVATE"

